### PR TITLE
EVAKA-3885: new output mode for occupancy report

### PR DESCRIPTION
**Pull request by Joosakur**
#### Summary
Report now has a mode which outputs capacity sum and caretaker count for each day in separate columns to better support calculating different averages and other statistics from the data.

#### Testing instructions
Might be easiest to test in staging env.

#### Checklist for pull request creator

- [ ] The code is consistent with the existing code base
- [ ] Tests have been written for the change (e2e, integration tests)
- [ ] The change has been tested locally
- [ ] The change conforms to the UX specifications
- [ ] The code is self-documenting or has been documented sufficiently, e.g., in the README
- [ ] The branch has been rebased against master before the PR was created

#### Checklist for pull request reviewer (copy to review text box)

```
- [ ] All changes in all changed files have been reviewed
- [ ] The code is consistent with the existing code base
- [ ] Tests have been written for the change (e2e, integration tests)
- [ ] The change has been tested locally
- [ ] The change conforms to the UX specifications
- [ ] The code is self-documenting or has been documented sufficiently, e.g., in the README
- [ ] The PR branch has been rebased against master and force pushed if necessary before merging
```

### CODE REVIEW

**Comment by kustaahuhtala** [comment]
I'm a bit confused. Should there be a percentage presentation here?
percentages

**Review by kustaahuhtala — CHANGES_REQUESTED** [review]
I think the representation should be in plain numbers, not percentages?

**Comment by Joosakur** [comment]
> I think the representation should be in plain numbers, not percentages?

indeed

**Comment by Joosakur** [comment]
prosenttimerkit poistettu

**Review by kustaahuhtala — APPROVED** [review]
Very nice. Perhaps wording on the report could be slightly improved, i.e. use something more informative than  "summa ja kasvattajamäärä erikseen".

**Pull request merged**
