### PR TITLE
Add service need option fee table

### PR DESCRIPTION
**Pull request by patari**
#### Summary

Allows to override default finance decision fees.

### CODE REVIEW

**Comment by akheron** [comment]
LGTM.

@Joosakur maybe you want to check this out too?

**Review by Joosakur — COMMENTED** [review]
Looks good to me too, but there's one test which fails if `v1_enabled` is set to false so that it actually tests v2. Not immediately sure why this test is affected. 🤔 

Screenshot 2023-08-28 at 14 28 08

**Comment by patari** [comment]
> Looks good to me too, but there's one test which fails if `v1_enabled` is set to false so that it actually tests v2. Not immediately sure why this test is affected. 🤔
> 
> Screenshot 2023-08-28 at 14 28 08

I think its related to https://github.com/espoon-voltti/evaka/pull/4022

**Comment by patari** [comment]
I guess V2 tests are run but not asserted when both v1 and v2 are enabled

**Review by Joosakur — APPROVED** [review]
ah, that test is broken in master too, I'll fix that

**Comment by Joosakur** [comment]
> I guess V2 tests are run but not asserted when both v1 and v2 are enabled

yeah, I couldn't think of easy way to run tests with two different configs. hopefully we can soon remove v1 altogether

**Pull request merged**
