### PR TITLE
Varda: remove unnecessarily strict application condition

### PR DESCRIPTION
**Pull request by jaahon**
#### Summary

Not all applications and placement proposals go through unit supervisors so this condition for finding a placement's application is unnecessarily strict. Just noticed this by accident.

### CODE REVIEW

**Comment by hruoho** [comment]
Hmm good catch! I still wonder though should we have _some_ condition there to prevent placements that will be rejected 🤔

**Comment by jaahon** [comment]
> Hmm good catch! I still wonder though should we have _some_ condition there to prevent placements that will be rejected 🤔

But doesn't `a.status IN ('ACTIVE')` already guarantee that? If a placement plan is rejected, it's replaced by a new one.

**Comment by hruoho** [comment]
> > Hmm good catch! I still wonder though should we have _some_ condition there to prevent placements that will be rejected 🤔
> 
> But doesn't `a.status IN ('ACTIVE')` already guarantee that? If a placement plan is rejected, it's replaced by a new one.

Ah yes... I believe it does 👍

**Review by hruoho — APPROVED** [review]
Let's ship it in and see what happens :)

**Pull request merged**
