### PR TITLE
Improve mobile staff attendance edit

### PR DESCRIPTION
**Pull request by patari**
#### Summary

https://github.com/espoon-voltti/evaka/pull/4344 part2

### CODE REVIEW

**Comment by akheron** [comment]
The back button at the top of the page goes back in history, which makes it hard to get back to the staff list page.

Possible fixes:
* The button could point to `.../staff-attendance/present`.
* If possible, avoid pushing new entries to history when opening the edit page

**Review by akheron — CHANGES_REQUESTED** [review]
The back button at the top of the page goes back in history, which makes it hard to get back to the staff list page.

Possible fixes:
* The button could point to `.../staff-attendance/present`.
* If possible, avoid pushing new entries to history when opening the edit page

**Comment by patari** [comment]
> The back button at the top of the page goes back in history, which makes it hard to get back to the staff list page.
> 
> Possible fixes:
> 
> * The button could point to `.../staff-attendance/present`.
> * If possible, avoid pushing new entries to history when opening the edit page

Fixed

**Comment by Wnt** [comment]
When editing previously added attendance, the error label overlaps delete button and makes it unclickable:
image

I think it would also be nice to add a lock icon to the save button to indicate that a PIN-code is needed to complete the edit:
image

**Comment by patari** [comment]
> When editing previously added attendance, the error label overlaps delete button and makes it unclickable: image
> 
> I think it would also be nice to add a lock icon to the save button to indicate that a PIN-code is needed to complete the edit: image

Fixed both!

**Review by akheron — APPROVED** [review]

**Pull request merged**
