### PR TITLE
EVAKA-UX: use async button quick mode on commonly used mobile actions

### PR DESCRIPTION
**Pull request by Joosakur**

### CODE REVIEW

**Comment by jaahon** [comment]
Instead of having a `quick` prop would it make more sense to just make `onSuccess` optional and call the callback immediately when the promise resolves? And maybe rename `onSuccess` to something like `afterSuccessAnimation` and reduce the animation duration.

**Comment by Joosakur** [comment]
> Instead of having a `quick` prop would it make more sense to just make `onSuccess` optional and call the callback immediately when the promise resolves? And maybe rename `onSuccess` to something like `afterSuccessAnimation` and reduce the animation duration.

Not sure I understand. Do you propose that there would be two optional callbacks, `onSuccess` and `afterSuccessAnimation`, where the first one is called immediately after promise is resolved and the latter after animation? So if in this case I would want to skip the animation, I would put the `history.goBack()` to `onSuccess` instead of `afterSuccessAnimation`? Although I'm not sure I even want to skip the animation entirely.

**Comment by jaahon** [comment]
> > Instead of having a `quick` prop would it make more sense to just make `onSuccess` optional and call the callback immediately when the promise resolves? And maybe rename `onSuccess` to something like `afterSuccessAnimation` and reduce the animation duration.
> 
> Not sure I understand. Do you propose that there would be two optional callbacks, `onSuccess` and `afterSuccessAnimation`, where the first one is called immediately after promise is resolved and the latter after animation? So if in this case I would want to skip the animation, I would put the `history.goBack()` to `onSuccess` instead of `afterSuccessAnimation`? Although I'm not sure I even want to skip the animation entirely.

What I mean is that the `onClick` callback can just do the navigation when the promise resolves, there is no need to do it in a separate callback.

But, another idea I got is that the `onSuccess` callback would be fired after about 500ms, but the success state would just be shown for a longer time. That way users see the success state for longer, but are not slowed down in cases where you are navigated out anyway and the successful state is implied anyway.

**Comment by Joosakur** [comment]
> But, another idea I got is that the `onSuccess` callback would be fired after about 500ms, but the success state would just be shown for a longer time. That way users see the success state for longer, but are not slowed down in cases where you are navigated out anyway and the successful state is implied anyway.

I decided to try this approach now

**Review by jaahon — APPROVED** [review]

**Pull request merged**
