### PR TITLE
EVAKA-4190 Enable messaging in prod for pilot units

### PR DESCRIPTION
**Pull request by kimifoud**
#### Summary

Prerequisites:
- [x] Suomi.fi has confirmed that keycloak certificate request is approved
- [x] Suomi.fi authentication works
- [x] VPN restriction is lifted https://github.com/espoon-voltti/evaka-infra/pull/428

### CODE REVIEW

**Comment by Joosakur** [comment]
Should we filter account list to only pilot unit group accounts?

**Comment by Joosakur** [comment]
Citizen side comes in separate PR? Maybe both should be enabled at the same time or else some citizen will end up getting emails about unread messages without actually being able to read them.

**Comment by kimifoud** [comment]
> Citizen side comes in separate PR? Maybe both should be enabled at the same time or else some citizen will end up getting emails about unread messages without actually being able to read them.

Ah, good catch. I didn't realize there was a separate feature flag config for citizen.

**Comment by kimifoud** [comment]
> Should we filter account list to only pilot unit group accounts?

Hmmm, maybe..? Should be pretty easy anyway.

**Review by reynders — APPROVED** [review]

**Comment by mikkopiu** [comment]
Also: don't merge this before the Keycloak realm's whitelisting is removed from the deployment (otherwise users will end up on a 403 nginx page).

**Pull request merged**
