### PR TITLE
EVAKA citizen header

### PR DESCRIPTION
**Pull request by jaahon**
#### Summary

Update the citizen header to match the UI specs.

### CODE REVIEW

**Review by kustaahuhtala — COMMENTED** [review]
Looks pretty good to me. Only issue I could find was with 12.9 inch iPad Pro, where the logout button is hidden.
Screenshot 2021-02-27 at 13 07 11

**Review by kustaahuhtala — CHANGES_REQUESTED** [review]
See my previous comment.

**Comment by jaahon** [comment]
> Looks pretty good to me. Only issue I could find was with 12.9 inch iPad Pro, where the logout button is hidden.
> Screenshot 2021-02-27 at 13 07 11

What's the size of the view? The amount of tabs when developing (messages tab is hidden in prod) makes the problem more pronounced, but there probably is a real problem with fitting all of the content in the header. I think I'll just hide the evaka logo at some screen widths.

**Comment by kustaahuhtala** [comment]
> > Looks pretty good to me. Only issue I could find was with 12.9 inch iPad Pro, where the logout button is hidden.
> > Screenshot 2021-02-27 at 13 07 11
> 
> What's the size of the view? The amount of tabs when developing (messages tab is hidden in prod) makes the problem more pronounced, but there probably is a real problem with fitting all of the content in the header. I think I'll just hide the evaka logo at some screen widths.

iPad 12 Pro in portrait is 1024 x 1336. The issue still remains, but if the tablet is turned to landscape mode, the logout button is visible.
Screenshot 2021-03-01 at 14 23 01

**Review by kustaahuhtala — APPROVED** [review]

**Comment by jaahon** [comment]
> > > Looks pretty good to me. Only issue I could find was with 12.9 inch iPad Pro, where the logout button is hidden.
> > > Screenshot 2021-02-27 at 13 07 11
> > 
> > 
> > What's the size of the view? The amount of tabs when developing (messages tab is hidden in prod) makes the problem more pronounced, but there probably is a real problem with fitting all of the content in the header. I think I'll just hide the evaka logo at some screen widths.
> 
> iPad 12 Pro in portrait is 1024 x 1336. The issue still remains, but if the tablet is turned to landscape mode, the logout button is visible.
> Screenshot 2021-03-01 at 14 23 01

Do you mean the issue is still there after my changes?

**Pull request merged**
