### PR TITLE
Add service need option name localization

### PR DESCRIPTION
**Pull request by patari**
#### Summary

Tampere uses service need options in citizen app -> option names must be localizable.

### CODE REVIEW

**Comment by patari** [comment]
No idea why codegen fails on CI. Works on my machine

**Comment by patari** [comment]
> No idea why codegen fails on CI. Works on my machine

Apparently multiple `ReplyToMessageBody`s in `messaging.ts` gets sorted in the wrong order on my machine. Fixed manually

**Review by akheron — APPROVED** [review]

**Comment by akheron** [comment]
Superseded by #1621

**Comment by huhtari** [comment]
Superseded, closing

**Pull request closed without merging**
