### PR TITLE
added finnish as second language to assistance measure type

### PR DESCRIPTION
**Pull request by mrosin**
Added enum value to other assistance measure type in db and frontend

### CODE REVIEW

**Comment by mrosin** [comment]
City of Oulu is tracking finnish as second language as other assistant measure. I was told this was discussed during PO meeting today

**Comment by mrosin** [comment]
@Gekkio tuo service-test failaa 
RUN ./circle-check-migrations.sh:

Yritin etsiä että mikäs filu toi on mutta ei löydy koko projektista. Mikäs tämä on?

**Comment by Gekkio** [comment]
https://github.com/espoon-voltti/evaka/blob/master/service/circle-check-migrations.sh

**Comment by mrosin** [comment]
Aivopieru. Onhan se siellä. emt miten mä sitä etsin enkä löytänyt

**Review by Gekkio — APPROVED** [review]

**Pull request merged**
